version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports: [ "3000:3000" ]
    volumes:
      - .:/app                # コードをボリュームにマウント
      - /app/node_modules     # node_modules を保護
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
    depends_on: [ db ]

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
